sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
     - php: nightly

install: composer install --dev

before_script: cp -f .env.example .env

script:
  - ./vendor/bin/phpcs --standard=PSR2 -s ./src
  - ./vendor/bin/phpunit
  - ./vendor/bin/parallel-lint --exclude vendor .
