sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
     - php: nightly

before_script: cp -f .env.example .env
install: composer install --dev
script: ./vendor/bin/phpunit
